-- AlterTable
ALTER TABLE `tbl_users` MODIFY `ip` VARCHAR(191) NULL,
    MODIFY `x` DOUBLE NOT NULL DEFAULT 0,
    MODIFY `y` DOUBLE NOT NULL DEFAULT 0,
    MODIFY `z` DOUBLE NOT NULL DEFAULT 0,
    MODIFY `totp` VARCHAR(191) NULL;
